// <auto-generated />

using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;


namespace Disunity.Management.Data.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    [Migration("20190901001951_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Disunity.Management.Models.PackageIdentifier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("PackageIdentifier");
                });

            modelBuilder.Entity("Disunity.Management.Models.ProfileMeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisunityDistroId");

                    b.Property<string>("Mods")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DisunityDistroId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Disunity.Management.Models.TargetMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ActiveProfileId");

                    b.Property<string>("DisplayName");

                    b.Property<string>("ExecutablePath");

                    b.Property<string>("ManagedPath");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.HasIndex("ActiveProfileId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Disunity.Management.Models.TargetProfile", b =>
                {
                    b.Property<Guid>("ProfileMetaId");

                    b.Property<int>("TargetMetaId");

                    b.HasKey("ProfileMetaId", "TargetMetaId");

                    b.HasIndex("TargetMetaId");

                    b.ToTable("TargetProfiles");
                });

            modelBuilder.Entity("Disunity.Management.Models.ProfileMeta", b =>
                {
                    b.HasOne("Disunity.Management.Models.PackageIdentifier", "DisunityDistro")
                        .WithMany()
                        .HasForeignKey("DisunityDistroId");
                });

            modelBuilder.Entity("Disunity.Management.Models.TargetMeta", b =>
                {
                    b.HasOne("Disunity.Management.Models.ProfileMeta", "ActiveProfile")
                        .WithMany()
                        .HasForeignKey("ActiveProfileId");
                });

            modelBuilder.Entity("Disunity.Management.Models.TargetProfile", b =>
                {
                    b.HasOne("Disunity.Management.Models.ProfileMeta", "ProfileMeta")
                        .WithMany("Targets")
                        .HasForeignKey("ProfileMetaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Disunity.Management.Models.TargetMeta", "TargetMeta")
                        .WithMany("Profiles")
                        .HasForeignKey("TargetMetaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
