version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: frontend
    volumes:
      - ./Frontend/ts:/Source/ts
      - ./Frontend/css:/Source/css
      - static-data:/Build

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DATABASE_URL}
      AdminUser__Email: ${ADMINUSER_EMAIL}
      AdminUser__Password: ${ADMINUSER_PASSWORD}
    ports:
      - 0.0.0.0:8000:80
    depends_on:
      - db
      - cache
    volumes:
      - static-data:/Frontend/dist
      - ./Disunity.Store/Pages:/app/Pages
      - ./Disunity.Store/Areas:/app/Areas

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:5.0.4-alpine3.9
    restart: always
    command: --maxmemory 200mb --maxmemory-policy allkeys-lru

  dotnet:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: build
    entrypoint: dotnet
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DATABASE_URL}
    volumes:
      - ./:/app

  release:
    build:
      context: .
      dockerfile: ./docker/release.Dockerfile
    volumes:
      - ./Release:/app/Release

volumes:
  db-data:
  static-data:
  built-static:
